### ISSUE TITLE
automate adding QA and Dev team to Jenkins 

### ISSUE THREAD

**Issue by aclipco** [fuchicorp/common_tools#97]
Fuchicorp Team,

we need to automate adding QA & Dev team members with correct privileges .

See the link below:

https://github.com/fuchicorp/common_tools/blob/7e9f01267e55c82cb2e8b595fd7b503f3913b549/charts/jenkins/values.yaml#L372

**Comment by fsadykov** [comment]
I have implemented adding qa and DEV  https://github.com/fuchicorp/common_tools/pull/99
